#!/bin/bash

set -e

echo "Pushing additional tags"
imageName=$DOCKER_REPO":40013"
docker tag $IMAGE_NAME $imageName
docker push $imageName

imageName=$DOCKER_REPO":4.0.0-alpha-40013"
docker tag $IMAGE_NAME $imageName
docker push $imageName