#!/bin/bash

set -e

imageName=$DOCKER_REPO":40009"
docker tag $IMAGE_NAME $imageName
docker push $imageName

imageName=$DOCKER_REPO":4.0.0-alpha-40009"
docker tag $IMAGE_NAME $imageName
docker push $imageName